import React from 'react';
import PageWrapper from '../components/PageWrapper';
import VisionSection from '../components/ui/vision-feature-section';
import { motion } from 'framer-motion';

const Vision = () => {
  return (
    <PageWrapper>
      <div className="bg-[#050507] min-h-screen text-white overflow-hidden">
        {/* Header Section */}
        <section className="pt-32 pb-16 px-6">
          <div className="max-w-5xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <h1 className="text-5xl md:text-7xl font-display font-black mb-6 tracking-tighter">
                Our <span className="text-primary text-glow-md">Vision</span>
              </h1>
              <p className="text-zinc-500 max-w-2xl mx-auto text-lg font-medium leading-relaxed">
                Empowering every investor with institutional-grade intelligence to conquer global markets.
              </p>
            </motion.div>
          </div>
        </section>

        {/* The Core Vision Section */}
        <VisionSection />

        {/* Secondary Vision Context */}
        <section className="py-32 border-t border-white/5">
            <div className="max-w-5xl mx-auto px-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                    <motion.div
                        initial={{ opacity: 0, x: -30 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.8 }}
                    >
                        <h2 className="text-3xl font-bold mb-6">Transparency First</h2>
                        <p className="text-zinc-400 leading-relaxed text-lg">
                            We believe that AI in finance shouldn't be a black box. Our vision includes providing full explainability for every prediction and trade signal generated by our system.
                        </p>
                    </motion.div>
                    <motion.div
                        initial={{ opacity: 0, x: 30 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.8 }}
                        className="bg-zinc-900/50 p-8 rounded-3xl border border-white/5 shadow-2xl backdrop-blur-sm"
                    >
                        <div className="space-y-6">
                            <div className="flex gap-4">
                                <div className="size-12 rounded-2xl bg-primary/20 flex items-center justify-center shrink-0">
                                    <div className="size-6 bg-primary rounded-full shadow-lg shadow-primary/50" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-lg">Ethical AI</h4>
                                    <p className="text-zinc-500 text-sm">Building models that respect market integrity and fairness.</p>
                                </div>
                            </div>
                            <div className="flex gap-4">
                                <div className="size-12 rounded-2xl bg-indigo-500/20 flex items-center justify-center shrink-0">
                                    <div className="size-6 bg-indigo-500 rounded-full shadow-lg shadow-indigo-500/50" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-lg">Universal Access</h4>
                                    <p className="text-zinc-500 text-sm">Bringing billionaire-level tools to the everyday investor.</p>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </div>
        </section>

        {/* Final Vision Statement */}
        <section className="py-40 text-center relative">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-px bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                className="max-w-3xl mx-auto px-6"
            >
                <h3 className="text-4xl font-bold mb-8">Ready to see the future?</h3>
                <button className="px-12 py-5 bg-primary text-white font-black rounded-2xl hover:scale-105 active:scale-95 transition-all shadow-[0_0_40px_rgba(123,92,240,0.5)] uppercase tracking-widest text-sm">
                    Join the Vision
                </button>
            </motion.div>
        </section>
      </div>
    </PageWrapper>
  );
};

export default Vision;
